### ISSUE TITLE
How to quick-switch between desktops?

### ISSUE THREAD

**Issue by cbenz** [brunetton/i3-workspacesgrid#1]
Hi there!

You told me (by chat) that it was possible to quickly switch between the current desktop and the most recently viewed one (like alt-tab with windows, but for desktops).

How do you do that?

I ask the question here to share with others.

**Comment by brunetton** [comment]
It's "bounding" feature. It only works with desktops that have a sortcut
(1-10 by default).
Example : you're on desktop 20, you want to go to desktop 1 to answer
someone on chat, you press the shortkey to go to 1, and once you're on 1,
pressing that same shortkey again brings you back to where you came back
(20).
This should go to the Readme, indeed

**Comment by cbenz** [comment]
OK then! Is it a feature from i3-workspacesgrid or from i3 itself?

**Comment by brunetton** [comment]
What feature ? The "bounding" feature ? Yes it's from i3-workspace-grid. Look at display_workspace() funciton.

**Comment by cbenz** [comment]
Thanks for your answer! I understand this is alpha software :-) But I'm really interested in the project, understanding and perhaps contributing!

So I still don't understand why you call it "bounding" feature (like attached?)? Or "bouncing"? Is it a typo?

It that's OK for you I'm doing a PR, just with your explanation in the README.

**Comment by brunetton** [comment]
Ooops, it's a typo; it was boucing. I call it like that on code; and "jump-back" in config file (=> to be homogenized).
You're of course very welcome to contribute to make all of this clearer !

**Comment by cbenz** [comment]
I'd like to be explicit about what I found: 
i3 already has a feature called "[workspace back and forth](http://build.i3wm.org/docs/userguide.html#_automatic_back_and_forth_when_switching_to_the_current_workspace
)" and I'd like to know if it would be feasible to use it directly, instead of coding it in your project ;-)

I can test it and tell you!

**Comment by brunetton** [comment]
:open_mouth: you make a good point ! I didn't noticed this i3 feature.

This calls into question the need to have the script running in "server" mode.
I can't make a clear decision about what is the "best" way to go: 
  - script called each time a workspace jump is trigger; this implies script init that is quite heavy (for now): ini file parsing, Docopt init 
  - "server" mode. Advantage: quick response

It both cases it is possible to use the `workspace_auto_back_and_forth` i3 option.

**Comment by brunetton** [comment]
> It both cases it is possible to use the workspace_auto_back_and_forth i3 option.

I should have said: In both cases it **would be** possible to use the workspace_auto_back_and_forth i3 option; it needs a little dev to adapt the script

**Comment by cbenz** [comment]
> This calls into question the need to have the script running in "server" mode.

In all cases I found that the decision to create a server was taken too quickly.

If it's to optimize the start of the script, let's optimize it really: profile it with the [right tools](https://www.huyng.com/posts/python-performance-analysis) first (in particular `line_profiler`). *Perhaps* it will show that `docopt` is not so slow, but INI parsing is. In each case there is a solution: replace `docopt` by `argparse`, or replace INI by a Python file which would be just sourced (and take advantage of native `.pyc` pre-compilation which acts like a cache).

Then, if there is still a need for a server-client architecture, prefer sockets [like i3 does](http://build.i3wm.org/docs/userguide.html#_interprocess_communication).
I didn't dig more about it.

This goes beyond the perimeter of this issue though :-)
